/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.disruta.view.cocina;

import com.disfruta.bean.admin.UsuarioDesktop;
import com.disfruta.bean.logistica.CocineroPlatos;
import com.disfruta.bean.logistica.DetallePedido;
import com.disfruta.gestion.admin.GestionUsuarioDesktop;
import com.disfruta.gestion.logistica.GestionDetallePedido;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;

/**
 *
 * @author Juape
 */
public class PanelCocina extends javax.swing.JPanel {
    protected ArrayList<ItemStaffSesion> staffCocina;
    public static ArrayList<CocineroPlatos> cocineros;
    /**
     * Creates new form PanelCocina
     */
    public PanelCocina() {
        try {
            init();
            initComponents();
            this.panelContainerProductos.setLayout(new GridLayout(25, 1, 10, 10));//gridLayout es una matriz (filas,columnas,margen de filas,margen de columnas)
            this.panelContainerProductos.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));// margenes internos para el panel
            this.panelContainerProductosEspera.setLayout(new GridLayout(10, 1, 10, 10));
            this.panelContainerProductosEspera.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
            GestionDetallePedido gp = new GestionDetallePedido();
            ArrayList<DetallePedido> lista = gp.listarTodos();
            for (int i = 0; i < lista.size(); i++) {
                DetallePedido d = lista.get(i);
                System.out.println("cantidad: " + d.getCantidad());
                System.out.println("mesa: " + d.getPedido().getMesa());
                PanelProductoPedidoCocina panel = new PanelProductoPedidoCocina(d,staffCocina,this.panelContainerProductos);
                this.panelContainerProductos.add(panel);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelCocina.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(PanelCocina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void init(){
        try {
            staffCocina=new ArrayList();
            ArrayList<UsuarioDesktop> users=new GestionUsuarioDesktop().listarStaffCocina();
            System.out.println("size cocina: "+users.size());
            cocineros=new ArrayList();
            for (int i = 0; i < users.size(); i++) {
                CocineroPlatos cocinero=new CocineroPlatos(users.get(i),new <DetallePedido>ArrayList());
                this.cocineros.add(cocinero);
                ItemStaffSesion obj=new ItemStaffSesion(users.get(i));
                staffCocina.add(obj);
            }
            System.out.println("staff cocina: "+staffCocina.size());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelCocina.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(PanelCocina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelContainerProductos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelContainerProductosEspera = new javax.swing.JPanel();
        btnConfigurarStaFfCocina = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panelContainerProductos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContainerProductosLayout = new javax.swing.GroupLayout(panelContainerProductos);
        panelContainerProductos.setLayout(panelContainerProductosLayout);
        panelContainerProductosLayout.setHorizontalGroup(
            panelContainerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        panelContainerProductosLayout.setVerticalGroup(
            panelContainerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelContainerProductos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Platos/ Tragos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panelContainerProductosEspera.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContainerProductosEsperaLayout = new javax.swing.GroupLayout(panelContainerProductosEspera);
        panelContainerProductosEspera.setLayout(panelContainerProductosEsperaLayout);
        panelContainerProductosEsperaLayout.setHorizontalGroup(
            panelContainerProductosEsperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        panelContainerProductosEsperaLayout.setVerticalGroup(
            panelContainerProductosEsperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(panelContainerProductosEspera);

        btnConfigurarStaFfCocina.setText("Configuración");
        btnConfigurarStaFfCocina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfigurarStaFfCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigurarStaFfCocinaActionPerformed(evt);
            }
        });

        jButton1.setText("ver empleados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(btnConfigurarStaFfCocina)
                .addGap(313, 313, 313))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfigurarStaFfCocina)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Lista de espera", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Platos/ Tragos");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfigurarStaFfCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigurarStaFfCocinaActionPerformed
        // TODO add your handling code here:
        DialogSesionStaffCocina dialog=new DialogSesionStaffCocina(null,true);
        dialog.panelCtnStaffCocina.setLayout(new GridLayout(6, 1, 10, 10));
        dialog.panelCtnStaffCocina.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        for (int i = 0; i < staffCocina.size(); i++) {
            System.out.println("enro aqui en configurar");
            dialog.panelCtnStaffCocina.add(staffCocina.get(i));
        }
        dialog.setVisible(true);
    }//GEN-LAST:event_btnConfigurarStaFfCocinaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < cocineros.size(); i++) {
            System.out.println("Cocinero: "+cocineros.get(i).getUsuario().getNombres());
            for (int j = 0; j < cocineros.get(i).getPlatos().size(); j++) {
                System.out.println("Plato: "+cocineros.get(i).getPlatos().get(j).getId());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        int p=this.jTabbedPane1.getSelectedIndex();
        if(p==1){
            for(int i=0;i<cocineros.size();i++){
                if(cocineros.get(i).getPlatos().size()>0){
                ItemCocineroPlatos item=new ItemCocineroPlatos(cocineros.get(i));
                this.panelContainerProductosEspera.add(item);
                }
            }
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfigurarStaFfCocina;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelContainerProductos;
    public javax.swing.JPanel panelContainerProductosEspera;
    // End of variables declaration//GEN-END:variables
}
