/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.disfruta.view.staff;

import com.disfruta.bean.admin.UsuarioDesktop;
import com.disfruta.bean.logistica.DetallePedido;
import com.disfruta.bean.logistica.Pedido;
import com.disfruta.bean.logistica.PresentacionPrecioVenta;
import com.disfruta.gestion.logistica.GestionDetallePedido;
import com.disfruta.gestion.logistica.GestionPedido;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import resources.auxiliar.FechaActual;
import resources.auxiliar.PaddingLeft;

/**
 *
 * @author Juape
 */
public class PanelStaff extends javax.swing.JPanel {

    protected int controlTab = 1;
    protected ArrayList<JPanel> pedidos;
    protected ArrayList<ItemPedidoEnviado> pedidosEnviados;

    /**
     * Creates new form PanelStaff
     */
    public PanelStaff() {
        try {
            this.pedidos = new ArrayList();
            this.pedidosEnviados = new ArrayList();
            System.out.println("fecha: "+FechaActual.formatoMysql());
            ArrayList<Pedido> pds=new GestionPedido().listarPedidosHoy(FechaActual.formatoMysql());
            System.out.println("pds_size: "+pds.size());
            for (int i = 0; i <pds.size(); i++) {
                ItemPedidoEnviado item=new ItemPedidoEnviado(pds.get(i));
                this.pedidosEnviados.add(item);
            }
            initComponents();
            PanelTabPedido nuevoPedido = new PanelTabPedido();
            this.TabPaneContainer.add(nuevoPedido, 0);
            this.TabPaneContainer.setIconAt(0, new ImageIcon(getClass().getResource("/images/icon_tab_edit.png")));        this.TabPaneContainer.setTitleAt(0, "0000 ");
            this.pedidos.add(nuevoPedido);
            this.TabPaneContainer.setSelectedIndex(0);
            
    //        JPanel panelTab=new JPanel();
    //        JScrollPane scroll=new JScrollPane();
    //        JPanel panel=new JPanel();
    //        panel.setLayout(new GridLayout(10, 1, 10, 10));//gridLayout es una matriz (filas,columnas,margen de filas,margen de columnas)
    //        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
    //        scroll.add(panel);
    //        panelTab.add(scroll);
    //        tabbedHistorial.setTitleAt(0,"Pedidos enviados");
    //        tabbedHistorial.setTitleAt(0,"Pedidos enviados");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelStaff.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(PanelStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblnumeromesa = new javax.swing.JLabel();
        btnVerPedido = new javax.swing.JButton();
        btnHistorialPedidos = new javax.swing.JButton();
        TabPaneContainer = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTerminarPedido = new javax.swing.JButton();
        txtMontoTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 252, 252));
        setMinimumSize(new java.awt.Dimension(960, 590));
        setPreferredSize(new java.awt.Dimension(960, 590));

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 25));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 25));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Pedidos");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("N° Mesa:");

        lblnumeromesa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblnumeromesa.setForeground(new java.awt.Color(102, 102, 102));
        lblnumeromesa.setText("0000");

        btnVerPedido.setBackground(new java.awt.Color(255, 255, 255));
        btnVerPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verPedido.png"))); // NOI18N
        btnVerPedido.setBorder(null);
        btnVerPedido.setBorderPainted(false);
        btnVerPedido.setContentAreaFilled(false);
        btnVerPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPedidoActionPerformed(evt);
            }
        });

        btnHistorialPedidos.setBackground(new java.awt.Color(102, 102, 102));
        btnHistorialPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnHistorialPedidos.png"))); // NOI18N
        btnHistorialPedidos.setBorderPainted(false);
        btnHistorialPedidos.setContentAreaFilled(false);
        btnHistorialPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(121, 121, 121)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblnumeromesa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(btnVerPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                .addComponent(btnHistorialPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerPedido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(lblnumeromesa)
                        .addComponent(jLabel1))
                    .addComponent(btnHistorialPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TabPaneContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabPaneContainer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabPaneContainerMouseClicked(evt);
            }
        });
        TabPaneContainer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabPaneContainerStateChanged(evt);
            }
        });
        TabPaneContainer.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                TabPaneContainerAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 935, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        TabPaneContainer.addTab("", new javax.swing.ImageIcon(getClass().getResource("/images/icon_tab_otro.png")), jPanel3); // NOI18N

        jPanel2.setBackground(new java.awt.Color(248, 248, 248));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Total: S/");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("05");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Prod.");

        btnTerminarPedido.setBackground(new java.awt.Color(229, 147, 35));
        btnTerminarPedido.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnTerminarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnTerminarPedido.setText("Terminar pedido");
        btnTerminarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTerminarPedido.setRequestFocusEnabled(false);
        btnTerminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarPedidoActionPerformed(evt);
            }
        });

        txtMontoTotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtMontoTotal.setText("0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)))
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMontoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnTerminarPedido)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnTerminarPedido)
                            .addComponent(txtMontoTotal))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabPaneContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TabPaneContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TabPaneContainerAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TabPaneContainerAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TabPaneContainerAncestorMoved

    private void TabPaneContainerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabPaneContainerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TabPaneContainerStateChanged

    private void TabPaneContainerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPaneContainerMouseClicked
        // TODO add your handling code here
        int position = this.TabPaneContainer.getSelectedIndex();
        System.out.println("in: " + position);
        System.out.println("control: " + this.controlTab);
        if (position == this.controlTab) {
            PanelTabPedido nuevoPedido = new PanelTabPedido();
            this.TabPaneContainer.add(nuevoPedido, this.controlTab);
            this.TabPaneContainer.setIconAt(this.controlTab, new ImageIcon(getClass().getResource("/images/icon_tab_edit.png")));
            this.TabPaneContainer.setTitleAt(this.controlTab, "0000 ");
            this.pedidos.add(nuevoPedido);
            this.controlTab = this.controlTab + 1;
            this.TabPaneContainer.setSelectedIndex(this.controlTab - 1);
        }
        String nummesa = this.TabPaneContainer.getTitleAt(position);
        this.lblnumeromesa.setText(nummesa);
    }//GEN-LAST:event_TabPaneContainerMouseClicked

    private void btnVerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPedidoActionPerformed
        // TODO add your handling code here:
        double subtotal = 0;
        int pedido = this.TabPaneContainer.getSelectedIndex();
        ArrayList<PanelProductoCartaItem> elegidos = new ArrayList();
        PanelTabPedido panel = (PanelTabPedido) this.pedidos.get(pedido);
        panel.llenarUltimaSeleccion();
        elegidos = panel.getListaProductosElegidos();
        System.out.println("size elegidos: " + elegidos.size());
        if (elegidos.size() > 0) {
            panel.getPanelContainerProductos().removeAll();
            for (int i = 0; i < elegidos.size(); i++) {
                System.out.println("listo");
                PanelProductoCartaItem panelProducto = elegidos.get(i);
                subtotal = subtotal + panelProducto.subtotal;
                panel.getPanelContainerProductos().add(panelProducto);
            }
            panel.getPanelContainerProductos().repaint();
            this.txtMontoTotal.setText(subtotal + "");
        } else {
            JOptionPane.showMessageDialog(this, "No hay productos agregados!");
        }

    }//GEN-LAST:event_btnVerPedidoActionPerformed

    private void btnTerminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarPedidoActionPerformed
        // TODO add your handling code here:
        int pedido = this.TabPaneContainer.getSelectedIndex();
        ArrayList<PanelProductoCartaItem> elegidos = new ArrayList();
        PanelTabPedido panel = (PanelTabPedido) this.pedidos.get(pedido);
        panel.llenarUltimaSeleccion();
        elegidos = panel.getListaProductosElegidos();
        if (elegidos.size() > 0) {
            int posStaff = panel.cboUsuarioStaff.getSelectedIndex();
            if (posStaff >= 0) {
                try {
                    Pedido pedidoRegister = new Pedido();
                    UsuarioDesktop usuario = panel.cboModelUsuario.getElement(posStaff);
                    String numeroMesa = panel.txtNumeroMesa.getText();
                    System.out.println("size elegidos para guardar: " + elegidos.size());
                    double montoTotal = 0;
                    ArrayList<DetallePedido> detalles = new ArrayList();
                    for (int i = 0; i < elegidos.size(); i++) {
                        PanelProductoCartaItem panelProducto = elegidos.get(i);
                        montoTotal = montoTotal + panelProducto.subtotal;
                        DetallePedido detalle = new DetallePedido();
                        detalle.setCantidad(Double.parseDouble(panelProducto.cantidad.getText()));
                        detalle.setSubtotal(panelProducto.subtotal);
                        detalle.setEstado("EN");
                        detalle.setComentario("Despacho normal");
                        PresentacionPrecioVenta presentacion = new PresentacionPrecioVenta();
                        presentacion.setPresentacion(panelProducto.presentacionSelect.getPresentacion());
                        presentacion.setProudcto(panelProducto.productoSelected);
                        detalle.setPresentacion(presentacion);
                        detalle.setTipoOperacion("i");
                        detalles.add(detalle);
                    }
                    pedidoRegister.setEstado("PD");
                    pedidoRegister.setEstadoPedido("A");
                    pedidoRegister.setMesa(numeroMesa);
                    pedidoRegister.setMontototal(montoTotal);
                    pedidoRegister.setTipo("E");
                    pedidoRegister.setUsuario(usuario);
                    pedidoRegister.setTipoOperacion("i");
                    //registramos en logtbc_pedido
                    GestionPedido gestionPedido = new GestionPedido();
                    gestionPedido.registrar(pedidoRegister);
                    Pedido ultimo = gestionPedido.getUltimoObject();

                    //registramos los productos en detalle_pedido
                    GestionDetallePedido gestionDetalle = new GestionDetallePedido();
                    for (int i = 0; i < detalles.size(); i++) {
                        DetallePedido objdetalle = detalles.get(i);
                        objdetalle.setPedido(ultimo);
                        objdetalle.setTipoOperacion("i");
                        gestionDetalle.registrar(objdetalle);
                    }

                    JOptionPane.showMessageDialog(this, "Pedido enviado !");
                    ItemPedidoEnviado item=new ItemPedidoEnviado(ultimo);
                    this.pedidosEnviados.add(item);
                    this.TabPaneContainer.remove(pedido);
                    if (pedido == 0) {
                        PanelTabPedido nuevoPedido = new PanelTabPedido();
                        this.TabPaneContainer.add(nuevoPedido, 0);
                        this.TabPaneContainer.setIconAt(0, new ImageIcon(getClass().getResource("/images/icon_tab_edit.png")));
                        this.TabPaneContainer.setTitleAt(0, "0000 ");
                        this.pedidos.add(nuevoPedido);
                        this.TabPaneContainer.setSelectedIndex(0);
                    }
                    this.txtMontoTotal.setText("");

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PanelStaff.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(PanelStaff.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un Staff !");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay productos agregados!");
        }
    }//GEN-LAST:event_btnTerminarPedidoActionPerformed

    private void btnHistorialPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialPedidosActionPerformed
        // TODO add your handling code here:
        System.out.println("entro");
        this.setLayout( null );
        PanelHistorialPedido panel=new PanelHistorialPedido();
        TabPaneContainer.setVisible(false);
        panel.setBounds(10,40,940,460);
        this.add(panel);
        this.validate();
        for (int i = 0; i < pedidosEnviados.size(); i++) {
            System.out.println("entro a pedido");
            panel.panelContainerPedidos.add(pedidosEnviados.get(i));
        }
    }//GEN-LAST:event_btnHistorialPedidosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabPaneContainer;
    private javax.swing.JButton btnHistorialPedidos;
    private javax.swing.JButton btnTerminarPedido;
    private javax.swing.JButton btnVerPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lblnumeromesa;
    private javax.swing.JLabel txtMontoTotal;
    // End of variables declaration//GEN-END:variables
}
