/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.disfruta.view.admin;

import com.disfruta.bean.admin.Menu;
import com.disfruta.bean.admin.MenuPerfil;
import com.disfruta.bean.admin.PerfilUsuario;
import com.disfruta.gestion.admin.GestionMenuPerfil;
import com.disfruta.gestion.admin.GestionPerfilUsuario;
import com.disfruta.util.jtree.Nodo;
import com.disfruta.util.jtree.TreeCheckBoxJava;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.ScrollPane;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.tree.DefaultTreeModel;
import resources.auxiliar.PaddingLeft;

/**
 *
 * @author user
 */
public class PanelPerfilUsuario extends javax.swing.JPanel {

    protected resources.tablemodel.ModelTablePerfilUsuario modelTablePerfilUser;
    protected DefaultTreeModel modelo = null;
    private String control = "nuevo";
    TreeCheckBoxJava chkbox = null;

    /**
     * Creates new form PanelPerfilUsuario
     */
    public PanelPerfilUsuario() throws ClassNotFoundException, Exception {
        init();
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        chkbox = new TreeCheckBoxJava();
        ScrollPane scroll = new ScrollPane();
        scroll.setSize(new Dimension(460, 500));
        scroll.add(chkbox);
        this.ctnArbol.add(scroll);
        this.tblPerfiles.setModel(modelTablePerfilUser);
        PaddingLeft.agregarpadding(txtDescripcionPerfil);
        this.cboEstado.setBackground(Color.WHITE);
    }

    private void init() {
        try {
            modelTablePerfilUser = new resources.tablemodel.ModelTablePerfilUsuario(new GestionPerfilUsuario().listar());

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelPerfilUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(PanelPerfilUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneltitlealmacen = new javax.swing.JPanel();
        logoalmacen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevoUsuario = new javax.swing.JButton();
        btnGuardarUsuario = new javax.swing.JButton();
        btnEliminarPerfil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcionPerfil = new javax.swing.JTextField();
        cboEstado = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPerfiles = new javax.swing.JTable();
        ctnArbol = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        paneltitlealmacen.setBackground(new java.awt.Color(238, 189, 122));
        paneltitlealmacen.setPreferredSize(new java.awt.Dimension(960, 60));

        logoalmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/almacen.gif"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Perfil de usuario");

        btnNuevoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevoUsuario.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        btnNuevoUsuario.setForeground(new java.awt.Color(229, 147, 35));
        btnNuevoUsuario.setText("Nuevo");
        btnNuevoUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        btnNuevoUsuario.setBorderPainted(false);
        btnNuevoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoUsuario.setFocusPainted(false);
        btnNuevoUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoUsuario.setOpaque(false);
        btnNuevoUsuario.setPreferredSize(new java.awt.Dimension(92, 30));
        btnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioActionPerformed(evt);
            }
        });

        btnGuardarUsuario.setBackground(new java.awt.Color(252, 242, 228));
        btnGuardarUsuario.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        btnGuardarUsuario.setForeground(new java.awt.Color(83, 71, 65));
        btnGuardarUsuario.setText("Guardar");
        btnGuardarUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        btnGuardarUsuario.setBorderPainted(false);
        btnGuardarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarUsuario.setFocusPainted(false);
        btnGuardarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarUsuario.setOpaque(false);
        btnGuardarUsuario.setPreferredSize(new java.awt.Dimension(92, 30));
        btnGuardarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarUsuarioActionPerformed(evt);
            }
        });

        btnEliminarPerfil.setBackground(new java.awt.Color(229, 147, 35));
        btnEliminarPerfil.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        btnEliminarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPerfil.setText("Eliminar");
        btnEliminarPerfil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        btnEliminarPerfil.setBorderPainted(false);
        btnEliminarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarPerfil.setFocusPainted(false);
        btnEliminarPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarPerfil.setOpaque(false);
        btnEliminarPerfil.setPreferredSize(new java.awt.Dimension(92, 30));
        btnEliminarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneltitlealmacenLayout = new javax.swing.GroupLayout(paneltitlealmacen);
        paneltitlealmacen.setLayout(paneltitlealmacenLayout);
        paneltitlealmacenLayout.setHorizontalGroup(
            paneltitlealmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltitlealmacenLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logoalmacen)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(193, 193, 193)
                .addComponent(btnNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        paneltitlealmacenLayout.setVerticalGroup(
            paneltitlealmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltitlealmacenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoalmacen)
                .addGap(16, 16, 16))
            .addGroup(paneltitlealmacenLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(paneltitlealmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneltitlealmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Descripción:");

        txtDescripcionPerfil.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        txtDescripcionPerfil.setToolTipText("");
        txtDescripcionPerfil.setAlignmentX(0.0F);
        txtDescripcionPerfil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));
        txtDescripcionPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescripcionPerfil.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtDescripcionPerfil.setName("txtusuario"); // NOI18N
        txtDescripcionPerfil.setPreferredSize(new java.awt.Dimension(280, 24));
        txtDescripcionPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionPerfilActionPerformed(evt);
            }
        });

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Desactivo" }));

        jLabel3.setText("Estado:");

        tblPerfiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPerfiles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblPerfiles.setSelectionBackground(new java.awt.Color(238, 189, 122));
        tblPerfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPerfilesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPerfiles);

        javax.swing.GroupLayout ctnArbolLayout = new javax.swing.GroupLayout(ctnArbol);
        ctnArbol.setLayout(ctnArbolLayout);
        ctnArbolLayout.setHorizontalGroup(
            ctnArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );
        ctnArbolLayout.setVerticalGroup(
            ctnArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneltitlealmacen, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDescripcionPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(78, 78, 78))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(ctnArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneltitlealmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDescripcionPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton1)
                        .addGap(0, 238, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ctnArbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed
        // TODO add your handling code here:
        this.txtDescripcionPerfil.setText("");
        this.cboEstado.setSelectedIndex(0);
        this.control = "nuevo";
//        this.itemsMenuSelect = new ArrayList();
        this.tblPerfiles.clearSelection();
    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

    private void btnGuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUsuarioActionPerformed

        String cad = this.txtDescripcionPerfil.getText();
        if (!(cad.equals(""))) {
            ArrayList<Nodo> nodos = new ArrayList();
            nodos = chkbox.getNodosStatus();
//            chkbox.mostrarArbolNodos();
            if (this.control.equals("nuevo")) {
                try {
                    GestionPerfilUsuario gestion = new GestionPerfilUsuario();
                    PerfilUsuario perfil = new PerfilUsuario();
                    perfil.setIdprefil(0);
                    perfil.setDescripcion(this.txtDescripcionPerfil.getText());
                    if (this.cboEstado.getSelectedIndex() == 0) {
                        perfil.setEstado("A");
                    } else {
                        perfil.setEstado("D");
                    }
                    perfil.setTipoOperacion("i");
                    gestion.registrar(perfil);

                    PerfilUsuario ultimoPerfil = gestion.getUltimoObject();
                    GestionMenuPerfil gm = new GestionMenuPerfil();
//                    System.out.println("size items menu: " + nodos.size());
                    for (int i = 0; i < nodos.size(); i++) {
                        Nodo nodo = nodos.get(i);
                        if (nodo.getSelected()) {
                            MenuPerfil menuPerfil = new MenuPerfil();
                            menuPerfil.setPerfil(ultimoPerfil);
                            menuPerfil.setMenu(nodo.getObj());
                            menuPerfil.setVisible("S");
                            menuPerfil.setEstado("A");
                            menuPerfil.setTipoOperacion("i");
                            for (int j = 0; j < nodo.getHijos().size(); j++) {
                                Nodo hijo1 = nodo.getHijos().get(j);
                                if (hijo1.getSelected()) {
                                    MenuPerfil menuHijo = new MenuPerfil();
                                    menuHijo.setPerfil(ultimoPerfil);
                                    menuHijo.setMenu(hijo1.getObj());
                                    menuHijo.setVisible("S");
                                    menuHijo.setEstado("A");
                                    menuHijo.setTipoOperacion("i");
                                    boolean contr=true;//quiere decir q no hay hijos con selected=true
                                    for (int k = 0; k < hijo1.getHijos().size(); k++) {
                                        Nodo hijo2 = hijo1.getHijos().get(k);
                                        if (hijo2.getSelected()) {
                                            contr=false;
                                            MenuPerfil menuHijo2 = new MenuPerfil();
                                            menuHijo2.setPerfil(ultimoPerfil);
                                            menuHijo2.setMenu(hijo2.getObj());
                                            menuHijo2.setVisible("S");
                                            menuHijo2.setEstado("A");
                                            menuHijo2.setTipoOperacion("i");
                                            String msg = gm.registrarMenu(menuHijo2);
                                            System.out.println("Insertado Nodo: "+menuHijo2.getMenu().getDescripcion());
                                        }
                                    }
                                    if(contr){
                                        for (int k = 0; k < hijo1.getHijos().size(); k++) {
                                            Nodo hi = hijo1.getHijos().get(k);
                                            MenuPerfil men = new MenuPerfil();
                                            men.setPerfil(ultimoPerfil);
                                            men.setMenu(hi.getObj());
                                            men.setVisible("S");
                                            men.setEstado("A");
                                            men.setTipoOperacion("i");
                                            String msg = gm.registrarMenu(men);
                                            System.out.println("Insertado Nodo: "+men.getMenu().getDescripcion());
                                        }
                                    }
                                    String msg = gm.registrarMenu(menuHijo);
                                    System.out.println("Insertado Nodo: "+menuHijo.getMenu().getDescripcion());
                                }
                                
                            }
                            String msg = gm.registrarMenu(menuPerfil);
                            System.out.println("Insertado Nodo: "+menuPerfil.getMenu().getDescripcion());
                        }
                    }

                    JOptionPane.showMessageDialog(this, "Registrado Correctamente !");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PanelPerfilUsuario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(PanelPerfilUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (this.control.equals("modificar")) {
//                GestionPerfilUsuario gestion = new GestionPerfilUsuario();
//                PerfilUsuario perfil = this.modelTablePerfilUser.getValue(this.tblPerfiles.getSelectedRow());
//                perfil.setTipoOperacion("a");
//                gestion.actualizar(perfil);
//
//                GestionMenuPerfil gm = new GestionMenuPerfil();
//                MenuPerfil menuP = new MenuPerfil();
//                menuP.setPerfil(perfil);
//                Menu omenu = new Menu();
//                omenu.setId(0);
//                menuP.setMenu(omenu);
//                menuP.setVisible("S");
//                menuP.setEstado("A");
//                menuP.setTipoOperacion("e");
//                gm.eliminar(menuP);
//                for (int i = 0; i < this.itemsMenuSelect.size(); i++) {
//                    MenuPerfil menuPerfil = new MenuPerfil();
//                    menuPerfil.setPerfil(perfil);
//                    menuPerfil.setMenu(this.itemsMenuSelect.get(i));
//                    menuPerfil.setVisible("S");
//                    menuPerfil.setEstado("A");
//                    menuPerfil.setTipoOperacion("i");
//                    gm.registrarMenu(menuPerfil);
//                }

                JOptionPane.showMessageDialog(this, "Actualizado Correctamente !");
            }
//            this.modelTablePerfilUser.setData(new GestionPerfilUsuario().listar());
            this.modelTablePerfilUser.fireTableDataChanged();
        } else {
            JOptionPane.showMessageDialog(this, "Llene todos los campos!");
        }
    }//GEN-LAST:event_btnGuardarUsuarioActionPerformed

    private void txtDescripcionPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionPerfilActionPerformed

    private void tblPerfilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPerfilesMouseClicked
        // TODO add your handling code here:
        int row = this.tblPerfiles.getSelectedRow();
        if (row >= 0) {
            PerfilUsuario perfil = this.modelTablePerfilUser.getValue(row);
            this.txtDescripcionPerfil.setText(perfil.getDescripcion());
            if (perfil.getEstado().equals("A")) {
                this.cboEstado.setSelectedIndex(0);
            } else {
                this.cboEstado.setSelectedIndex(1);
            }
        }
        this.control = "modificar";
    }//GEN-LAST:event_tblPerfilesMouseClicked

    private void btnEliminarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPerfilActionPerformed
        // TODO add your handling code here:
        int row = this.tblPerfiles.getSelectedRow();
        if (row >= 0) {
            try {
                GestionMenuPerfil gmp = new GestionMenuPerfil();
                PerfilUsuario perfil = this.modelTablePerfilUser.getValue(row);
                MenuPerfil menuPerfil = new MenuPerfil();
                menuPerfil.setPerfil(perfil);
                Menu omenu = new Menu();
                omenu.setId(0);
                menuPerfil.setMenu(omenu);
                menuPerfil.setVisible("S");
                menuPerfil.setEstado("A");
                menuPerfil.setTipoOperacion("e");
                gmp.eliminar(menuPerfil);

                GestionPerfilUsuario gperfil = new GestionPerfilUsuario();
                perfil.setTipoOperacion("e");
                gperfil.eliminar(perfil);

                JOptionPane.showMessageDialog(this, "Eliminado Correctamente !");
                this.modelTablePerfilUser.setData(new GestionPerfilUsuario().listar());
                this.modelTablePerfilUser.fireTableDataChanged();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PanelPerfilUsuario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(PanelPerfilUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnEliminarPerfilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        chkbox.selectedCheckBox();
        System.out.println("nnn");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarPerfil;
    private javax.swing.JButton btnGuardarUsuario;
    private javax.swing.JButton btnNuevoUsuario;
    private javax.swing.JComboBox cboEstado;
    private javax.swing.JPanel ctnArbol;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logoalmacen;
    private javax.swing.JPanel paneltitlealmacen;
    private javax.swing.JTable tblPerfiles;
    private javax.swing.JTextField txtDescripcionPerfil;
    // End of variables declaration//GEN-END:variables
}