/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.disfruta.view.logistica;

import com.disfruta.bean.logistica.FamiliaProducto;
import com.disfruta.bean.logistica.ProductoCarta;
import com.disfruta.gestion.logistica.GestionDetalleInsumo;
import com.disfruta.gestion.logistica.GestionFamiliaProducto;
import com.disfruta.gestion.logistica.GestionPresentacionPrecioVenta;
import com.disfruta.gestion.logistica.GestionProductoCarta;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import resources.auxiliar.PaddingLeft;

/**
 *
 * @author Juape
 */
public class PanelProductoCarta extends javax.swing.JPanel {

    private resources.comboboxmodel.CboModelFamiliaProducto modelCboCategoria;
    private resources.tablemodel.ModelTableProductoCarta modelTableProductoCarta;
    protected resources.tablemodel.ModelTablePresentacionPrecioVenta modelTablePrecioVenta;
    protected String control = "nuevo";

    /**
     * Creates new form PanelFormulas
     */
    public PanelProductoCarta() {
        try {
            init();
            initComponents();
            this.cboCategoria.setModel(modelCboCategoria);
            this.tblProductoVenta.setModel(modelTableProductoCarta);
            this.tblMostrarPresentacion.setModel(modelTablePrecioVenta);
            PaddingLeft.agregarpadding(txtNombreProductoCarta);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelProductoCarta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(PanelProductoCarta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void init() throws ClassNotFoundException, Exception {
        this.modelCboCategoria = new resources.comboboxmodel.CboModelFamiliaProducto(new GestionFamiliaProducto().listar());
        this.modelTableProductoCarta = new resources.tablemodel.ModelTableProductoCarta(new GestionProductoCarta().listar());
        this.modelTablePrecioVenta = new resources.tablemodel.ModelTablePresentacionPrecioVenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneltitlealmacen = new javax.swing.JPanel();
        logoalmacen = new javax.swing.JLabel();
        btnNuevoProducto = new javax.swing.JButton();
        btnGuardarProductoCarta = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreProductoCarta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionProdCarta = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductoVenta = new javax.swing.JTable();
        btnEditarPresentacion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMostrarPresentacion = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cboDespachadoen = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(960, 590));
        setPreferredSize(new java.awt.Dimension(960, 590));

        paneltitlealmacen.setBackground(new java.awt.Color(238, 189, 122));
        paneltitlealmacen.setPreferredSize(new java.awt.Dimension(960, 60));

        logoalmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/almacen.gif"))); // NOI18N

        btnNuevoProducto.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevoProducto.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        btnNuevoProducto.setForeground(new java.awt.Color(229, 147, 35));
        btnNuevoProducto.setText("Nuevo");
        btnNuevoProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        btnNuevoProducto.setBorderPainted(false);
        btnNuevoProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoProducto.setFocusPainted(false);
        btnNuevoProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoProducto.setOpaque(false);
        btnNuevoProducto.setPreferredSize(new java.awt.Dimension(92, 30));
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });

        btnGuardarProductoCarta.setBackground(new java.awt.Color(252, 242, 228));
        btnGuardarProductoCarta.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        btnGuardarProductoCarta.setForeground(new java.awt.Color(83, 71, 65));
        btnGuardarProductoCarta.setText("Guardar");
        btnGuardarProductoCarta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        btnGuardarProductoCarta.setBorderPainted(false);
        btnGuardarProductoCarta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarProductoCarta.setFocusPainted(false);
        btnGuardarProductoCarta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarProductoCarta.setOpaque(false);
        btnGuardarProductoCarta.setPreferredSize(new java.awt.Dimension(92, 30));
        btnGuardarProductoCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProductoCartaActionPerformed(evt);
            }
        });

        btnEliminarProducto.setBackground(new java.awt.Color(229, 147, 35));
        btnEliminarProducto.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        btnEliminarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        btnEliminarProducto.setBorderPainted(false);
        btnEliminarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarProducto.setFocusPainted(false);
        btnEliminarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarProducto.setOpaque(false);
        btnEliminarProducto.setPreferredSize(new java.awt.Dimension(92, 30));
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Producto de venta");

        javax.swing.GroupLayout paneltitlealmacenLayout = new javax.swing.GroupLayout(paneltitlealmacen);
        paneltitlealmacen.setLayout(paneltitlealmacenLayout);
        paneltitlealmacenLayout.setHorizontalGroup(
            paneltitlealmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltitlealmacenLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(logoalmacen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(160, 160, 160)
                .addComponent(btnNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarProductoCarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        paneltitlealmacenLayout.setVerticalGroup(
            paneltitlealmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltitlealmacenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoalmacen))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltitlealmacenLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(paneltitlealmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarProductoCarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jLabel2.setText("Codigo de producto:");

        jLabel3.setText("1245-20014-25");

        jLabel4.setText("Nombre de producto de venta:");

        txtNombreProductoCarta.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        txtNombreProductoCarta.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreProductoCarta.setText("Nombre de producto");
        txtNombreProductoCarta.setToolTipText("");
        txtNombreProductoCarta.setAlignmentX(0.0F);
        txtNombreProductoCarta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));
        txtNombreProductoCarta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreProductoCarta.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtNombreProductoCarta.setName("txtusuario"); // NOI18N
        txtNombreProductoCarta.setPreferredSize(new java.awt.Dimension(280, 24));
        txtNombreProductoCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoCartaActionPerformed(evt);
            }
        });

        jLabel5.setText("Categoría (Producto en carta):");

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Descripción:");

        txtDescripcionProdCarta.setColumns(20);
        txtDescripcionProdCarta.setForeground(new java.awt.Color(153, 153, 153));
        txtDescripcionProdCarta.setRows(5);
        txtDescripcionProdCarta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jScrollPane1.setViewportView(txtDescripcionProdCarta);

        tblProductoVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Presentación comercial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductoVenta.getTableHeader().setReorderingAllowed(false);
        tblProductoVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoVentaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProductoVenta);
        tblProductoVenta.getColumnModel().getColumn(0).setResizable(false);
        tblProductoVenta.getColumnModel().getColumn(1).setResizable(false);

        btnEditarPresentacion.setText("a");
        btnEditarPresentacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPresentacionActionPerformed(evt);
            }
        });

        jLabel7.setText("Editar presentación comercial de venta (carta)");

        tblMostrarPresentacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Presentación comercial", "Precio (S/)", "Proporción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblMostrarPresentacion);
        tblMostrarPresentacion.getColumnModel().getColumn(1).setResizable(false);
        tblMostrarPresentacion.getColumnModel().getColumn(2).setResizable(false);

        jLabel8.setText("Despachado en:");

        cboDespachadoen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- SELECCIONE -", "COCINA", "BAR" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneltitlealmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtNombreProductoCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboDespachadoen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEditarPresentacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneltitlealmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreProductoCarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(cboDespachadoen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditarPresentacion)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(95, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreProductoCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoCartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoCartaActionPerformed

    private void btnEditarPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPresentacionActionPerformed
        // TODO add your handling code here:
        int p = this.tblProductoVenta.getSelectedRow();
        if (p >= 0) {
            try {
                ProductoCarta producto = this.modelTableProductoCarta.getValue(p);
                DialogPresComercialCarta dialog = new DialogPresComercialCarta(null, true, producto);
                dialog.setVisible(true);
                this.modelTablePrecioVenta.setData(new GestionPresentacionPrecioVenta().listarPorProducto(producto));
                this.modelTablePrecioVenta.fireTableDataChanged();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PanelProductoCarta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(PanelProductoCarta.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Registre un nuevo producto y/o seleccione uno de la lista");
        }
    }//GEN-LAST:event_btnEditarPresentacionActionPerformed

    private void btnGuardarProductoCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductoCartaActionPerformed
        // TODO add your handling code here:
        String nom = this.txtNombreProductoCarta.getText();
        int r = this.cboCategoria.getSelectedIndex();
        int p=this.cboDespachadoen.getSelectedIndex();
        if (r >= 0 && p>0 && !(nom.equals(""))) {
            if (this.control.equals("nuevo")) {
                ProductoCarta pro = new ProductoCarta();
                pro.setNombre(this.txtNombreProductoCarta.getText());
                pro.setDescripcion(this.txtDescripcionProdCarta.getText());
                pro.setDespachadoen(this.cboDespachadoen.getSelectedItem().toString());
                pro.setTipoOperacion("i");
                int pos = this.cboCategoria.getSelectedIndex();
                FamiliaProducto fami = (FamiliaProducto) this.modelCboCategoria.getElement(pos);
                pro.setFamilia(fami);
                GestionProductoCarta gestion = new GestionProductoCarta();
                gestion.registrar(pro);
                JOptionPane.showMessageDialog(this, "Registrado correctamente!");
            } else if (this.control.equals("modificar")) {
                int row = this.tblProductoVenta.getSelectedRow();
                if (row >= 0) {
                    this.control = "nuevo";
                    ProductoCarta pro = this.modelTableProductoCarta.getValue(row);
                    pro.setNombre(this.txtNombreProductoCarta.getText());
                    pro.setDescripcion(this.txtDescripcionProdCarta.getText());
                    pro.setDespachadoen(this.cboDespachadoen.getSelectedItem().toString());
                    pro.setTipoOperacion("a");
                    int pos = this.cboCategoria.getSelectedIndex();
                    FamiliaProducto fami = (FamiliaProducto) this.modelCboCategoria.getElement(pos);
                    pro.setFamilia(fami);
                    GestionProductoCarta gestion = new GestionProductoCarta();
                    gestion.actualizar(pro);
                    JOptionPane.showMessageDialog(this, "Actualizado correctamente!");
                } else {
                    JOptionPane.showMessageDialog(this, "Esta en estado modificar. Seleccione un producto de la tabla o presione en NUEVO");
                }
            }
            try {
                this.modelTableProductoCarta.setData(new GestionProductoCarta().listar());
                this.modelTableProductoCarta.fireTableDataChanged();
                this.txtDescripcionProdCarta.setText("");
                this.txtNombreProductoCarta.setText("");
                this.modelTablePrecioVenta.setData(new ArrayList());
                this.modelTablePrecioVenta.fireTableDataChanged();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PanelProductoCarta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(PanelProductoCarta.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Llene los campos !");
        }

    }//GEN-LAST:event_btnGuardarProductoCartaActionPerformed

    private void tblProductoVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoVentaMouseClicked
        try {
            // TODO add your handling code here:
            int p = this.tblProductoVenta.getSelectedRow();
            if (p >= 0) {
                this.control = "modificar";
                ProductoCarta producto = this.modelTableProductoCarta.getValue(p);
                this.txtNombreProductoCarta.setText(producto.getNombre());
                this.txtDescripcionProdCarta.setText(producto.getDescripcion());                
                this.cboCategoria.setSelectedItem(producto.getFamilia().getV_familia().toString());
                this.cboDespachadoen.setSelectedItem(producto.getDespachadoen());
                this.modelTablePrecioVenta.setData(new GestionPresentacionPrecioVenta().listarPorProducto(producto));
                this.modelTablePrecioVenta.fireTableDataChanged();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelProductoCarta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(PanelProductoCarta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tblProductoVentaMouseClicked

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        // TODO add your handling code here:
        this.control = "nuevo";
        this.txtDescripcionProdCarta.setText("");
        this.txtNombreProductoCarta.setText("");
        this.cboCategoria.setSelectedItem("");
        this.modelTablePrecioVenta.setData(new ArrayList());
        this.modelTablePrecioVenta.fireTableDataChanged();
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        // TODO add your handling code here:
        int r = this.tblProductoVenta.getSelectedRow();
        if (r >= 0 && this.control.equals("modificar")) {
            try {
                this.control = "nuevo";
                ProductoCarta producto = this.modelTableProductoCarta.getValue(r);
                //eliminamos el producto de la tabla detalle_insumo                
                producto.setTipoOperacion("e2");
                String rp = new GestionDetalleInsumo().eliminarPorProducto(producto);
                //eliminamos el producto de la tabla logtbc_precio_presentacion
                producto.setTipoOperacion("e1");
                String rp1 = new GestionPresentacionPrecioVenta().eliminarPorProducto(producto);
                //eliminamos de la tabla logtbc_producto_carta
                producto.setTipoOperacion("e");
                GestionProductoCarta gestion = new GestionProductoCarta();
                String rp2 = gestion.eliminar(producto);

                JOptionPane.showMessageDialog(this, "Eliminado correctamente!");
                this.txtDescripcionProdCarta.setText("");
                this.txtNombreProductoCarta.setText("");
                this.cboCategoria.setSelectedItem("");
                this.modelTableProductoCarta.setData(gestion.listar());
                this.modelTableProductoCarta.fireTableDataChanged();
                this.modelTablePrecioVenta.setData(new ArrayList());
                this.modelTablePrecioVenta.fireTableDataChanged();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PanelProductoCarta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(PanelProductoCarta.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnEliminarProductoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarPresentacion;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnGuardarProductoCarta;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JComboBox cboCategoria;
    private javax.swing.JComboBox cboDespachadoen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logoalmacen;
    private javax.swing.JPanel paneltitlealmacen;
    private javax.swing.JTable tblMostrarPresentacion;
    private javax.swing.JTable tblProductoVenta;
    private javax.swing.JTextArea txtDescripcionProdCarta;
    private javax.swing.JTextField txtNombreProductoCarta;
    // End of variables declaration//GEN-END:variables
}
