/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.disfruta.view.logistica;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import javax.swing.border.Border;

/**
 *
 * @author Juape
 */
public class PanelOrdenDeCompra extends javax.swing.JPanel {

    /**
     * Creates new form PanelOrdenDeCompra
     */
    public PanelOrdenDeCompra() {
        initComponents();
    }
    
    public void activarCajaBuscar(JTextField campo){
        campo.setSize(130, 22);
        campo.setBackground(Color.WHITE);
        Border border = BorderFactory.createLineBorder(Color.decode("#999999"));
        campo.setBorder(border);
        campo.setText("  ");
        campo.requestFocus(true);
    }
    
    public void desactivarCajaBuscar(JTextField campo,String name){
        campo.setBackground(null);
        campo.setBorder(null);
        campo.setText("  "+name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneltitlealmacen = new javax.swing.JPanel();
        logoalmacen = new javax.swing.JLabel();
        btnNuevoAlmacen = new javax.swing.JButton();
        btnNuevoAlmacen1 = new javax.swing.JButton();
        btnNuevoAlmacen2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboProveedores = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboMoneda = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cboFormaPago = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cboAlmacenEntrega = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtFechaRecepcion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFechaRecepcion1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReferencia = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        txtCantidadProducto = new javax.swing.JTextField();
        txtPrecioProducto = new javax.swing.JTextField();
        cboPresentacionproducto = new javax.swing.JComboBox();
        cboUnidadProducto = new javax.swing.JComboBox();
        cboMonedaProducto = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtBuscarCodigo = new javax.swing.JTextField();
        btnBuscarCodigo = new javax.swing.JButton();
        txtBuscarProveedor = new javax.swing.JTextField();
        btnBuscarProveedor = new javax.swing.JButton();
        txtBuscarReferencia = new javax.swing.JTextField();
        btnBuscarReferencia = new javax.swing.JButton();
        txtBuscarFechaEmision = new javax.swing.JTextField();
        btnBuscarFechaEmision = new javax.swing.JButton();
        txtBuscarFechaRecepcion = new javax.swing.JTextField();
        btnBuscarFechaRecepcion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOrdenes = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(960, 590));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(960, 590));

        paneltitlealmacen.setBackground(new java.awt.Color(238, 189, 122));
        paneltitlealmacen.setPreferredSize(new java.awt.Dimension(960, 60));

        logoalmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/almacen.gif"))); // NOI18N

        btnNuevoAlmacen.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevoAlmacen.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        btnNuevoAlmacen.setForeground(new java.awt.Color(229, 147, 35));
        btnNuevoAlmacen.setText("Nuevo");
        btnNuevoAlmacen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        btnNuevoAlmacen.setBorderPainted(false);
        btnNuevoAlmacen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoAlmacen.setFocusPainted(false);
        btnNuevoAlmacen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoAlmacen.setOpaque(false);
        btnNuevoAlmacen.setPreferredSize(new java.awt.Dimension(92, 30));

        btnNuevoAlmacen1.setBackground(new java.awt.Color(252, 242, 228));
        btnNuevoAlmacen1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        btnNuevoAlmacen1.setForeground(new java.awt.Color(83, 71, 65));
        btnNuevoAlmacen1.setText("Guardar");
        btnNuevoAlmacen1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        btnNuevoAlmacen1.setBorderPainted(false);
        btnNuevoAlmacen1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoAlmacen1.setFocusPainted(false);
        btnNuevoAlmacen1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoAlmacen1.setOpaque(false);
        btnNuevoAlmacen1.setPreferredSize(new java.awt.Dimension(92, 30));

        btnNuevoAlmacen2.setBackground(new java.awt.Color(229, 147, 35));
        btnNuevoAlmacen2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        btnNuevoAlmacen2.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoAlmacen2.setText("Eliminar");
        btnNuevoAlmacen2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        btnNuevoAlmacen2.setBorderPainted(false);
        btnNuevoAlmacen2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoAlmacen2.setFocusPainted(false);
        btnNuevoAlmacen2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoAlmacen2.setOpaque(false);
        btnNuevoAlmacen2.setPreferredSize(new java.awt.Dimension(92, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Orden de compra: ");

        jLabel9.setText("7008-1245");

        javax.swing.GroupLayout paneltitlealmacenLayout = new javax.swing.GroupLayout(paneltitlealmacen);
        paneltitlealmacen.setLayout(paneltitlealmacenLayout);
        paneltitlealmacenLayout.setHorizontalGroup(
            paneltitlealmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltitlealmacenLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(logoalmacen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(102, 102, 102)
                .addComponent(btnNuevoAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNuevoAlmacen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNuevoAlmacen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneltitlealmacenLayout.setVerticalGroup(
            paneltitlealmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltitlealmacenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoalmacen))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltitlealmacenLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(paneltitlealmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoAlmacen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoAlmacen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(960, 300));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(960, 300));

        jLabel2.setText("03 de julio de 2014");

        jLabel3.setText("Proveedor:");

        cboProveedores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Referencia:");

        jLabel5.setText("Moneda:");

        cboMoneda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Forma de pago:");

        cboFormaPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Almacen de recepción:");

        cboAlmacenEntrega.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Fecha de recepción:");

        txtFechaRecepcion.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        txtFechaRecepcion.setForeground(new java.awt.Color(153, 153, 153));
        txtFechaRecepcion.setText("   dia/mes/año");
        txtFechaRecepcion.setToolTipText("");
        txtFechaRecepcion.setAlignmentX(0.0F);
        txtFechaRecepcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));
        txtFechaRecepcion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtFechaRecepcion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtFechaRecepcion.setName("txtusuario"); // NOI18N
        txtFechaRecepcion.setPreferredSize(new java.awt.Dimension(280, 24));
        txtFechaRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaRecepcionActionPerformed(evt);
            }
        });

        jLabel10.setText("Lugar de recepción:");

        txtFechaRecepcion1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        txtFechaRecepcion1.setForeground(new java.awt.Color(153, 153, 153));
        txtFechaRecepcion1.setText("   Dirección del almacen");
        txtFechaRecepcion1.setToolTipText("");
        txtFechaRecepcion1.setAlignmentX(0.0F);
        txtFechaRecepcion1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));
        txtFechaRecepcion1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtFechaRecepcion1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtFechaRecepcion1.setName("txtusuario"); // NOI18N
        txtFechaRecepcion1.setPreferredSize(new java.awt.Dimension(280, 24));
        txtFechaRecepcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaRecepcion1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Observaciones:");

        txtReferencia.setColumns(20);
        txtReferencia.setForeground(new java.awt.Color(153, 153, 153));
        txtReferencia.setLineWrap(true);
        txtReferencia.setRows(5);
        txtReferencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jScrollPane1.setViewportView(txtReferencia);

        txtObservaciones.setColumns(20);
        txtObservaciones.setForeground(new java.awt.Color(153, 153, 153));
        txtObservaciones.setLineWrap(true);
        txtObservaciones.setRows(5);
        txtObservaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jScrollPane2.setViewportView(txtObservaciones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(cboProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(cboAlmacenEntrega, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(txtFechaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(txtFechaRecepcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaRecepcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboAlmacenEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Orden de compra", jPanel1);

        jLabel12.setText("Código:");

        jLabel13.setText("Nombre de producto:");

        jLabel14.setText("Presentación comercial:");

        jLabel15.setText("Cantidad:");

        jLabel16.setText("Unidad:");

        jLabel17.setText("Precio de compra:");

        jLabel18.setText("Moneda");

        txtCodigoProducto.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        txtCodigoProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigoProducto.setToolTipText("");
        txtCodigoProducto.setAlignmentX(0.0F);
        txtCodigoProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));
        txtCodigoProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodigoProducto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtCodigoProducto.setName("txtusuario"); // NOI18N
        txtCodigoProducto.setPreferredSize(new java.awt.Dimension(280, 24));
        txtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProductoActionPerformed(evt);
            }
        });

        txtNombreProducto.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        txtNombreProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreProducto.setToolTipText("");
        txtNombreProducto.setAlignmentX(0.0F);
        txtNombreProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));
        txtNombreProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreProducto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtNombreProducto.setName("txtusuario"); // NOI18N
        txtNombreProducto.setPreferredSize(new java.awt.Dimension(280, 24));
        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });

        txtCantidadProducto.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        txtCantidadProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtCantidadProducto.setToolTipText("");
        txtCantidadProducto.setAlignmentX(0.0F);
        txtCantidadProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));
        txtCantidadProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCantidadProducto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtCantidadProducto.setName("txtusuario"); // NOI18N
        txtCantidadProducto.setPreferredSize(new java.awt.Dimension(280, 24));
        txtCantidadProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadProductoActionPerformed(evt);
            }
        });

        txtPrecioProducto.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        txtPrecioProducto.setForeground(new java.awt.Color(153, 153, 153));
        txtPrecioProducto.setToolTipText("");
        txtPrecioProducto.setAlignmentX(0.0F);
        txtPrecioProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));
        txtPrecioProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPrecioProducto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtPrecioProducto.setName("txtusuario"); // NOI18N
        txtPrecioProducto.setPreferredSize(new java.awt.Dimension(280, 24));
        txtPrecioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioProductoActionPerformed(evt);
            }
        });

        cboPresentacionproducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboUnidadProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboMonedaProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Add");

        jScrollPane4.setOpaque(false);
        jScrollPane4.setPreferredSize(new java.awt.Dimension(450, 220));

        tblProductos.setForeground(new java.awt.Color(128, 128, 128));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Contenido", "Presentación comercial", "Cantidad", "Precio", "Moneda", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setToolTipText("");
        tblProductos.setAlignmentX(0.0F);
        tblProductos.setAlignmentY(0.0F);
        tblProductos.setAutoscrolls(false);
        tblProductos.setColumnSelectionAllowed(true);
        tblProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblProductos.setGridColor(new java.awt.Color(204, 204, 255));
        tblProductos.setMinimumSize(new java.awt.Dimension(900, 150));
        tblProductos.setRowHeight(30);
        tblProductos.setRowMargin(3);
        tblProductos.setShowHorizontalLines(false);
        tblProductos.setShowVerticalLines(false);
        tblProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblProductos);
        tblProductos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblProductos.getColumnModel().getColumn(0).setResizable(false);
        tblProductos.getColumnModel().getColumn(1).setResizable(false);
        tblProductos.getColumnModel().getColumn(2).setResizable(false);
        tblProductos.getColumnModel().getColumn(3).setResizable(false);
        tblProductos.getColumnModel().getColumn(4).setResizable(false);
        tblProductos.getColumnModel().getColumn(5).setResizable(false);
        tblProductos.getColumnModel().getColumn(6).setResizable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(cboPresentacionproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(cboUnidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cboMonedaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPresentacionproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboUnidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMonedaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Productos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(250, 233, 211));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));

        txtBuscarCodigo.setBackground(new java.awt.Color(250, 233, 211));
        txtBuscarCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBuscarCodigo.setForeground(new java.awt.Color(83, 71, 65));
        txtBuscarCodigo.setText("Codigo");
        txtBuscarCodigo.setToolTipText("");
        txtBuscarCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 233, 211)));
        txtBuscarCodigo.setMinimumSize(new java.awt.Dimension(130, 20));
        txtBuscarCodigo.setPreferredSize(new java.awt.Dimension(130, 20));
        txtBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarCodigoActionPerformed(evt);
            }
        });
        txtBuscarCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarCodigoFocusLost(evt);
            }
        });

        btnBuscarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnBuscar.jpg"))); // NOI18N
        btnBuscarCodigo.setToolTipText("");
        btnBuscarCodigo.setBorderPainted(false);
        btnBuscarCodigo.setContentAreaFilled(false);
        btnBuscarCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCodigo.setPreferredSize(new java.awt.Dimension(18, 18));
        btnBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCodigoActionPerformed(evt);
            }
        });

        txtBuscarProveedor.setBackground(new java.awt.Color(250, 233, 211));
        txtBuscarProveedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBuscarProveedor.setForeground(new java.awt.Color(83, 71, 65));
        txtBuscarProveedor.setText("Proveedor");
        txtBuscarProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 233, 211)));
        txtBuscarProveedor.setMinimumSize(new java.awt.Dimension(130, 20));
        txtBuscarProveedor.setPreferredSize(new java.awt.Dimension(130, 20));
        txtBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarProveedorActionPerformed(evt);
            }
        });
        txtBuscarProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarProveedorFocusLost(evt);
            }
        });

        btnBuscarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnBuscar.jpg"))); // NOI18N
        btnBuscarProveedor.setToolTipText("");
        btnBuscarProveedor.setBorderPainted(false);
        btnBuscarProveedor.setContentAreaFilled(false);
        btnBuscarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarProveedor.setPreferredSize(new java.awt.Dimension(18, 18));

        txtBuscarReferencia.setBackground(new java.awt.Color(250, 233, 211));
        txtBuscarReferencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBuscarReferencia.setForeground(new java.awt.Color(83, 71, 65));
        txtBuscarReferencia.setText("Referencia");
        txtBuscarReferencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 233, 211)));
        txtBuscarReferencia.setPreferredSize(new java.awt.Dimension(130, 17));
        txtBuscarReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarReferenciaActionPerformed(evt);
            }
        });
        txtBuscarReferencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarReferenciaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarReferenciaFocusLost(evt);
            }
        });

        btnBuscarReferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnBuscar.jpg"))); // NOI18N
        btnBuscarReferencia.setToolTipText("");
        btnBuscarReferencia.setBorderPainted(false);
        btnBuscarReferencia.setContentAreaFilled(false);
        btnBuscarReferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarReferencia.setPreferredSize(new java.awt.Dimension(18, 18));

        txtBuscarFechaEmision.setBackground(new java.awt.Color(250, 233, 211));
        txtBuscarFechaEmision.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBuscarFechaEmision.setForeground(new java.awt.Color(83, 71, 65));
        txtBuscarFechaEmision.setText("Fecha de emisión");
        txtBuscarFechaEmision.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 233, 211)));
        txtBuscarFechaEmision.setPreferredSize(new java.awt.Dimension(130, 17));
        txtBuscarFechaEmision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarFechaEmisionActionPerformed(evt);
            }
        });
        txtBuscarFechaEmision.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFechaEmisionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFechaEmisionFocusLost(evt);
            }
        });

        btnBuscarFechaEmision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnBuscar.jpg"))); // NOI18N
        btnBuscarFechaEmision.setToolTipText("");
        btnBuscarFechaEmision.setBorderPainted(false);
        btnBuscarFechaEmision.setContentAreaFilled(false);
        btnBuscarFechaEmision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarFechaEmision.setPreferredSize(new java.awt.Dimension(18, 18));

        txtBuscarFechaRecepcion.setBackground(new java.awt.Color(250, 233, 211));
        txtBuscarFechaRecepcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBuscarFechaRecepcion.setForeground(new java.awt.Color(83, 71, 65));
        txtBuscarFechaRecepcion.setText("Fecha de recepción");
        txtBuscarFechaRecepcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 233, 211)));
        txtBuscarFechaRecepcion.setPreferredSize(new java.awt.Dimension(130, 17));
        txtBuscarFechaRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarFechaRecepcionActionPerformed(evt);
            }
        });
        txtBuscarFechaRecepcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFechaRecepcionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFechaRecepcionFocusLost(evt);
            }
        });

        btnBuscarFechaRecepcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnBuscar.jpg"))); // NOI18N
        btnBuscarFechaRecepcion.setToolTipText("");
        btnBuscarFechaRecepcion.setBorderPainted(false);
        btnBuscarFechaRecepcion.setContentAreaFilled(false);
        btnBuscarFechaRecepcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarFechaRecepcion.setPreferredSize(new java.awt.Dimension(18, 18));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setForeground(new java.awt.Color(250, 233, 211));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setForeground(new java.awt.Color(250, 233, 211));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setForeground(new java.awt.Color(250, 233, 211));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jScrollPane3.setOpaque(false);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(450, 220));

        tblOrdenes.setForeground(new java.awt.Color(128, 128, 128));
        tblOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblOrdenes.setToolTipText("");
        tblOrdenes.setAlignmentX(0.0F);
        tblOrdenes.setAlignmentY(0.0F);
        tblOrdenes.setAutoscrolls(false);
        tblOrdenes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblOrdenes.setGridColor(new java.awt.Color(204, 204, 255));
        tblOrdenes.setMinimumSize(new java.awt.Dimension(900, 150));
        tblOrdenes.setRowHeight(30);
        tblOrdenes.setRowMargin(3);
        tblOrdenes.setShowHorizontalLines(false);
        tblOrdenes.setShowVerticalLines(false);
        tblOrdenes.setTableHeader(null);
        jScrollPane3.setViewportView(tblOrdenes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnBuscarReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(txtBuscarFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarFechaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarFechaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarFechaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscarFechaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneltitlealmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneltitlealmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaRecepcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaRecepcionActionPerformed

    private void txtFechaRecepcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaRecepcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaRecepcion1ActionPerformed

    private void txtBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCodigoActionPerformed

    private void txtBuscarCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarCodigoFocusGained
        // TODO add your handling code here:
        activarCajaBuscar(this.txtBuscarCodigo);
    }//GEN-LAST:event_txtBuscarCodigoFocusGained

    private void txtBuscarCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarCodigoFocusLost
        // TODO add your handling code here:
        desactivarCajaBuscar(this.txtBuscarCodigo,"Código");
    }//GEN-LAST:event_txtBuscarCodigoFocusLost

    private void btnBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCodigoActionPerformed

    private void txtBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProveedorActionPerformed

    private void txtBuscarProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarProveedorFocusGained
        // TODO add your handling code here:
        activarCajaBuscar(this.txtBuscarProveedor);
    }//GEN-LAST:event_txtBuscarProveedorFocusGained

    private void txtBuscarProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarProveedorFocusLost
        // TODO add your handling code here:
        desactivarCajaBuscar(this.txtBuscarProveedor,"Proveedor");
    }//GEN-LAST:event_txtBuscarProveedorFocusLost

    private void txtBuscarReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarReferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarReferenciaActionPerformed

    private void txtBuscarReferenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarReferenciaFocusGained
        // TODO add your handling code here:
        activarCajaBuscar(this.txtBuscarReferencia);
    }//GEN-LAST:event_txtBuscarReferenciaFocusGained

    private void txtBuscarReferenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarReferenciaFocusLost
        // TODO add your handling code here:
        desactivarCajaBuscar(this.txtBuscarReferencia,"Referencia");
    }//GEN-LAST:event_txtBuscarReferenciaFocusLost

    private void txtBuscarFechaEmisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarFechaEmisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarFechaEmisionActionPerformed

    private void txtBuscarFechaEmisionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFechaEmisionFocusGained
        // TODO add your handling code here:
        activarCajaBuscar(this.txtBuscarFechaEmision);
    }//GEN-LAST:event_txtBuscarFechaEmisionFocusGained

    private void txtBuscarFechaEmisionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFechaEmisionFocusLost
        // TODO add your handling code here:
        desactivarCajaBuscar(this.txtBuscarFechaEmision,"Fecha de emisión");
    }//GEN-LAST:event_txtBuscarFechaEmisionFocusLost

    private void txtBuscarFechaRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarFechaRecepcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarFechaRecepcionActionPerformed

    private void txtBuscarFechaRecepcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFechaRecepcionFocusGained
        // TODO add your handling code here:
        activarCajaBuscar(this.txtBuscarFechaRecepcion);
    }//GEN-LAST:event_txtBuscarFechaRecepcionFocusGained

    private void txtBuscarFechaRecepcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFechaRecepcionFocusLost
        // TODO add your handling code here:
        desactivarCajaBuscar(this.txtBuscarFechaRecepcion,"Fecha de recepción");
    }//GEN-LAST:event_txtBuscarFechaRecepcionFocusLost

    private void txtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoActionPerformed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void txtCantidadProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadProductoActionPerformed

    private void txtPrecioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCodigo;
    private javax.swing.JButton btnBuscarFechaEmision;
    private javax.swing.JButton btnBuscarFechaRecepcion;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnBuscarReferencia;
    private javax.swing.JButton btnNuevoAlmacen;
    private javax.swing.JButton btnNuevoAlmacen1;
    private javax.swing.JButton btnNuevoAlmacen2;
    private javax.swing.JComboBox cboAlmacenEntrega;
    private javax.swing.JComboBox cboFormaPago;
    private javax.swing.JComboBox cboMoneda;
    private javax.swing.JComboBox cboMonedaProducto;
    private javax.swing.JComboBox cboPresentacionproducto;
    private javax.swing.JComboBox cboProveedores;
    private javax.swing.JComboBox cboUnidadProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logoalmacen;
    private javax.swing.JPanel paneltitlealmacen;
    private javax.swing.JTable tblOrdenes;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscarCodigo;
    private javax.swing.JTextField txtBuscarFechaEmision;
    private javax.swing.JTextField txtBuscarFechaRecepcion;
    private javax.swing.JTextField txtBuscarProveedor;
    private javax.swing.JTextField txtBuscarReferencia;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtFechaRecepcion;
    private javax.swing.JTextField txtFechaRecepcion1;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextArea txtReferencia;
    // End of variables declaration//GEN-END:variables
}
