/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.disfruta.view.logistica;

import com.disfruta.bean.logistica.Almacen;
import com.disfruta.bean.logistica.ControlStock;
import com.disfruta.bean.logistica.Insumo;
import com.disfruta.gestion.logistica.GestionAlmacen;
import com.disfruta.gestion.logistica.GestionControlStock;
import com.disfruta.gestion.logistica.GestionInsumo;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import resources.tablemodel.ModelTableControlStock;

/**
 *
 * @author user
 */
public class PanelControlStock extends javax.swing.JPanel {

    private resources.comboboxmodel.CboModelAlmacen modelCboAlmacen;
    private resources.comboboxmodel.CboModelInsumo modelCboInsumo;
    private ModelTableControlStock tablastock;
    private String controlsave = "guardar";
    private ControlStock objselect=null;

    /**
     * Creates new form PanelControlStock
     */
    public PanelControlStock() {
        init();
        initComponents();
        this.cboAlmacen.setModel(modelCboAlmacen);
        this.cboInsumo.setModel(modelCboInsumo);
        this.tblcontrolstock.setModel(tablastock);
    }

    private void init() {
        try {
            ArrayList<Almacen> listaAlamcenes = new GestionAlmacen().listar();
            this.modelCboAlmacen = new resources.comboboxmodel.CboModelAlmacen(listaAlamcenes);
            ArrayList<Insumo> listaInsumos = new GestionInsumo().listar();
            this.modelCboInsumo = new resources.comboboxmodel.CboModelInsumo(listaInsumos);
            this.tablastock = new resources.tablemodel.ModelTableControlStock(new GestionControlStock().listar());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelControlStock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(PanelControlStock.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneltitlealmacen = new javax.swing.JPanel();
        logoalmacen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevoAlmacen = new javax.swing.JButton();
        btnGuardarControl = new javax.swing.JButton();
        btnEliminarInsumo = new javax.swing.JButton();
        cboAlmacen = new javax.swing.JComboBox();
        cboInsumo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcontrolstock = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        paneltitlealmacen.setBackground(new java.awt.Color(238, 189, 122));
        paneltitlealmacen.setPreferredSize(new java.awt.Dimension(960, 60));

        logoalmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/almacen.gif"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Control de Stock");

        btnNuevoAlmacen.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevoAlmacen.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        btnNuevoAlmacen.setForeground(new java.awt.Color(229, 147, 35));
        btnNuevoAlmacen.setText("Nuevo");
        btnNuevoAlmacen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        btnNuevoAlmacen.setBorderPainted(false);
        btnNuevoAlmacen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoAlmacen.setFocusPainted(false);
        btnNuevoAlmacen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoAlmacen.setOpaque(false);
        btnNuevoAlmacen.setPreferredSize(new java.awt.Dimension(92, 30));
        btnNuevoAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAlmacenActionPerformed(evt);
            }
        });

        btnGuardarControl.setBackground(new java.awt.Color(252, 242, 228));
        btnGuardarControl.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        btnGuardarControl.setForeground(new java.awt.Color(83, 71, 65));
        btnGuardarControl.setText("Guardar");
        btnGuardarControl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        btnGuardarControl.setBorderPainted(false);
        btnGuardarControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarControl.setFocusPainted(false);
        btnGuardarControl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarControl.setOpaque(false);
        btnGuardarControl.setPreferredSize(new java.awt.Dimension(92, 30));
        btnGuardarControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarControlActionPerformed(evt);
            }
        });

        btnEliminarInsumo.setBackground(new java.awt.Color(229, 147, 35));
        btnEliminarInsumo.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        btnEliminarInsumo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarInsumo.setText("Eliminar");
        btnEliminarInsumo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        btnEliminarInsumo.setBorderPainted(false);
        btnEliminarInsumo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarInsumo.setFocusPainted(false);
        btnEliminarInsumo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarInsumo.setOpaque(false);
        btnEliminarInsumo.setPreferredSize(new java.awt.Dimension(92, 30));
        btnEliminarInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarInsumoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneltitlealmacenLayout = new javax.swing.GroupLayout(paneltitlealmacen);
        paneltitlealmacen.setLayout(paneltitlealmacenLayout);
        paneltitlealmacenLayout.setHorizontalGroup(
            paneltitlealmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltitlealmacenLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logoalmacen)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(193, 193, 193)
                .addComponent(btnNuevoAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        paneltitlealmacenLayout.setVerticalGroup(
            paneltitlealmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltitlealmacenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoalmacen)
                .addGap(16, 16, 16))
            .addGroup(paneltitlealmacenLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(paneltitlealmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneltitlealmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNuevoAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardarControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cboAlmacen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboInsumo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Almacén:");

        jLabel3.setText("Insumo:");

        jLabel4.setText("Stock actual:");

        jLabel5.setText("Precio venta actual:");

        tblcontrolstock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblcontrolstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcontrolstockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcontrolstock);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneltitlealmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtstock)
                                .addComponent(cboAlmacen, 0, 285, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(cboInsumo, 0, 330, Short.MAX_VALUE)
                                .addComponent(txtprecio))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneltitlealmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoAlmacenActionPerformed

    private void btnGuardarControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarControlActionPerformed
        try {
            // TODO add your handling code here:

            int pi = this.cboInsumo.getSelectedIndex();
            int pa = this.cboAlmacen.getSelectedIndex();
            if (pi > -1 && pa > -1 && !this.txtstock.getText().equals("") && !this.txtprecio.getText().equals("")) {
                ControlStock control = new ControlStock();
                control.setInsumo(this.modelCboInsumo.getElement(pi));
                control.setAlmacen(this.modelCboAlmacen.getElement(pa));
                control.setStock(Double.parseDouble(this.txtstock.getText()));
                control.setPrecioventa(Double.parseDouble(this.txtprecio.getText()));
                if (this.controlsave.equalsIgnoreCase("guardar")) {
                    control.setTipoOperacion("i");
                    GestionControlStock gestionControl = new GestionControlStock();
                    gestionControl.registrar(control);
                    JOptionPane.showMessageDialog(null, "Registrado correctamente.");
                    this.tablastock.setData(gestionControl.listar());
                    this.tblcontrolstock.setModel(tablastock);
                    this.tablastock.fireTableDataChanged();
                } else {
                    if (this.controlsave.equalsIgnoreCase("modificar")) {
                        control.setIdcontrol(objselect.getIdcontrol());
                        control.setTipoOperacion("a");
                        GestionControlStock gestionControl = new GestionControlStock();
                        gestionControl.actualizar(control);
                        JOptionPane.showMessageDialog(null, "Actualizado correctamente.");
                        this.tablastock.setData(gestionControl.listar());
                        this.tblcontrolstock.setModel(tablastock);
                        this.tablastock.fireTableDataChanged();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Llene todos los campos!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelControlStock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(PanelControlStock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarControlActionPerformed
    private void btnEliminarInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarInsumoActionPerformed

    private void tblcontrolstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcontrolstockMouseClicked
        // TODO add your handling code here:
        int pos = this.tblcontrolstock.getSelectedRow();
        if (pos >= 0) {
            ControlStock control = this.tablastock.getValue(pos);
            objselect=control;
            this.cboAlmacen.setSelectedItem(control.getAlmacen().getDescripcion());
            this.cboInsumo.setSelectedItem(control.getInsumo().getNombre());
            this.txtprecio.setText(control.getPrecioventa() + "");
            this.txtstock.setText(control.getStock() + "");
            this.controlsave = "modificar";
        }
    }//GEN-LAST:event_tblcontrolstockMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarInsumo;
    private javax.swing.JButton btnGuardarControl;
    private javax.swing.JButton btnNuevoAlmacen;
    private javax.swing.JComboBox cboAlmacen;
    private javax.swing.JComboBox cboInsumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoalmacen;
    private javax.swing.JPanel paneltitlealmacen;
    private javax.swing.JTable tblcontrolstock;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
}
